# Generated by Django 4.0.4 on 2022-11-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_rename_user_id_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='book_id',
            field=models.CharField(max_length=100),
        ),
    ]
